name: Trigger CI
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'
      - '.github/**'
      - '.circleci/**'
      - 'demo/**'
      - '*.md'
      - 'LICENSE.txt'
      - 'PROJECT'
      - '.gitignore'
      - '.golangci-required.yml'
      - '.golangci.yml'
      - '.goreleaser.yaml'
      - '.images'

jobs:
  update-release-sha:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
      - name: Trigger CI with latest commit details
        if: ${{ !env.ACT }}
        run: |
          GITHUB_MESSAGE='${{ github.event.head_commit.message }}'
          if [ -z "$GITHUB_SHA" ]; then
            GITHUB_SHA=$(git rev-parse HEAD)
            GITHUB_MESSAGE=$(git log --format=%B -n 1 ${GITHUB_SHA})
          fi
          gh workflow run --repo syntasso/ci "Kratix" -f sha=$GITHUB_SHA -f message=$GITHUB_MESSAGE
        env:
          GH_TOKEN: ${{ secrets.GH_ACTION_TRIGGER_TOKEN }}
